# Generated by Django 2.0 on 2019-12-31 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voting', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('birthdate', models.DateField(null=True, verbose_name='Birthdate')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Sex')),
                ('related_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('province', models.CharField(choices=[('S', 'Sevillistán'), ('H', 'Huelvistán'), ('C', 'Cadistán')], max_length=1, null=True, verbose_name='Province')),
                ('employment', models.CharField(blank=True, choices=[('M', 'Militant'), ('B', 'Baron'), ('S', 'Senator'), ('P', 'President')], max_length=1, null=True, verbose_name='Employment')),
                ('related_political_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PoliticalParty', to='voting.PoliticalParty')),
            ],
        ),
    ]
